CREATE TABLE Stage_LopHoc_Error (
    id_Stage_LopHoc_Error NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Ma_lop VARCHAR2(5),
    Ten_lop NVARCHAR2(255) NOT NULL,
    id_rule_violated NUMBER,
    createdAt TIMESTAMP
);
CREATE TABLE Stage_Học_sinh_Error (
    id_Stage_Học_sinh_Error NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Mã_học_sinh VARCHAR2(5),
    Họ_tên NVARCHAR2(255) NOT NULL,
    Ngày_sinh DATE NOT NULL,
    Giới_tính NVARCHAR2(10) NOT NULL,
    Malop VARCHAR2(5),
    id_rule_violated NUMBER,
    createdAt TIMESTAMP
);
CREATE TABLE Stage_MonHoc_Error (
    id_Stage_MonHoc_Error NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    MaMH VARCHAR2(5),
    TenMH VARCHAR2(255) NOT NULL,
    id_rule_violated NUMBER,
    createdAt TIMESTAMP
);
CREATE TABLE Stage_Diem_Error (
    id_Stage_Diem_Error NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    MaHS VARCHAR2(5),
    MaMH VARCHAR2(5),
    Diem NUMBER(5,2),
    id_rule_violated NUMBER,
    createdAt TIMESTAMP
);
