CREATE TABLE DIM_LOPHOC (
    MaLop_SK NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,  -- Surrogate Key with auto-increment
    MaLop_NK VARCHAR2(5) NOT NULL,  -- Natural Key
    tên_lớp NVARCHAR2(255),  -- Class name
    siso NUMBER,  -- Number of students
    createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Record creation date
    UpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- Last update timestamp
);


CREATE TABLE DIM_HOCSINH (
    MaHS_SK NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,  -- Surrogate Key with auto-increment
    MaHS_NK VARCHAR2(5) NOT NULL,  -- Natural Key
    Hovaten NVARCHAR2(255),  -- Student's full name
    ngaySinh DATE,  -- Date of birth
    gioitinh NVARCHAR2(50),  -- Gender
    malopSK NUMBER NOT NULL,  -- Surrogate Key for DIM_LOPHOC
    createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Record creation date
    UpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Last update timestamp
    CONSTRAINT FK_HocSinh_LopHoc_DDS FOREIGN KEY (malopSK) REFERENCES DIM_LOPHOC(MaLop_SK)
);

CREATE TABLE DIM_MONHOC (
    MaMH_SK NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,  -- Surrogate Key with auto-increment
    MaMH_NK VARCHAR2(5) NOT NULL,  -- Natural Key
    TenMH NVARCHAR2(255),  -- Subject name
    SoTC NUMBER,  -- Number of credits
    createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Record creation date
    UpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Last update timestamp
    isViable CHAR(1)  -- BIT equivalent in Oracle: CHAR(1) with 'Y' or 'N'
);

CREATE TABLE FACT_THONGKE (
    FACT_SK NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,  -- Surrogate Key with auto-increment
    MaHS_SK NUMBER NOT NULL,  -- Surrogate Key for DIM_HOCSINH
    MaMH_SK NUMBER NOT NULL,  -- Surrogate Key for DIM_MONHOC
    Diem NUMBER(5,2),  -- Score
    IsPass CHAR(1),  -- BIT equivalent in Oracle: CHAR(1) with 'Y' or 'N'
    PassCount NUMBER,  -- Pass count
    FailCount NUMBER,  -- Fail count
    FailCountByLop NUMBER,  -- Fail count by class
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Record creation date
    UpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Last update timestamp
    CONSTRAINT FK_ThongKe_HocSinh_DDS FOREIGN KEY (MaHS_SK) REFERENCES DIM_HOCSINH(MaHS_SK),
    CONSTRAINT FK_ThongKe_MonHoc_DDS FOREIGN KEY (MaMH_SK) REFERENCES DIM_MONHOC(MaMH_SK)
);
